### ISSUE TITLE
How to Set Up

### ISSUE THREAD

**Issue by hotwheels47125** [hansonw/itunesfm#2]
I am incredibly excited to have found this script, after logging 10 years (+) of last.fm plays, and having recently lost my iTunes data. However, I'm having a lot of trouble understanding where to get started with this script.
I feel like I need to input my last.fm name somewhere in one of the files, but I just don't know where to begin.
Any help offered is greatly appreciated! This script sounds like a dream come true!!

-CW-

**Comment by hansonw** [comment]
Hey neat! Glad you found it. It's a parameter to the script - did you read https://github.com/hansonw/itunesfm#usage?

**Comment by hotwheels47125** [comment]
I have, yes. Haha, several times over and over throughout the day trying to tackle the script in any new way I can. Truthfully, I am completely new to this, and while I feel like I need to type that "npm install -g itunesfm itunesfm <last.fm username>" in to something, I just don't know what?

**Comment by hansonw** [comment]
Which operating system do you use? You need node.js installed, and then you have to enter those commands in a terminal or command prompt.

**Comment by hotwheels47125** [comment]
I just got it running, thanks to your prompt and straight to the point response! You are officially one of my music library heroes! Thank you, so very much, for your work on this magnificent script, and flawless aid!
