### ISSUE TITLE
limit param out of bounds (1-1000)

### ISSUE THREAD

**Issue by RudeySH** [hansonw/itunesfm#4]
Doesn't seem to work. I'm on Windows. Do I have too many tracks or something?

    Fetching play counts from last.fm..
    { error: 6, message: 'limit param out of bounds (1-1000)' }

**Comment by hansonw** [comment]
Ah, looks like last.fm tightened their API limits, the code asks for 5000:
https://github.com/hansonw/itunesfm/blob/master/src/lastfm.js#L60

If you're familiar with JS just modify that line to 1000, otherwise I can
fix it sometime soon

**Comment by hansonw** [comment]
Published a new version (1.1.0).
