### ISSUE TITLE
Compatibility with Music.app on 10.15

### ISSUE THREAD

**Issue by NotKlemant** [hansonw/itunesfm#7]
Hi there! I found this script to be super useful, but unfortunately it doesn't seem to work with Music.app on Catalina. Do you think there would be any way to make it compatible with this new version? 

Thank you very much!

**Comment by hansonw** [comment]
Fixed! Try `npm install -g hansonw/itunesfm` to get the new version.

**Comment by NotKlemant** [comment]
Thank you very much for the update!
